# Generated by Django 5.2.5 on 2025-08-10 10:33

import clients.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.CharField(default=clients.models.generate_custom_client_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lastVisit', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nbpersonnes', models.PositiveIntegerField()),
                ('destinations', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
