# Generated by Django 5.2.5 on 2025-08-10 10:33

import activites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('idActivite', models.CharField(default=activites.models.generate_custom_activite_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyenne', 'Moyenne'), ('difficile', 'Difficile')], max_length=20)),
                ('priceAdult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceChild', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groupSizeMin', models.PositiveIntegerField()),
                ('groupSizeMax', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('includes', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('guideRequired', models.BooleanField()),
                ('guideName', models.CharField(blank=True, max_length=100, null=True)),
                ('guidePhone', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField()),
                ('reviews', models.PositiveIntegerField()),
                ('seasons', models.JSONField(default=list)),
                ('favorite', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activites',
            },
        ),
    ]
