# Generated by Django 5.2.5 on 2025-08-10 10:33

import django.db.models.deletion
import django.utils.timezone
import factures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.CharField(default=factures.models.generate_facture_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('dateTravel', models.DateField(blank=True, null=True)),
                ('dateReturn', models.DateField(blank=True, null=True)),
                ('dateCreated', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('confirmé', 'Confirmé'), ('payé', 'Payé'), ('en_attente', 'En attente'), ('annulé', 'Annulé'), ('en_cours', 'En cours'), ('annule', 'Annulé')], default='en_attente', max_length=50)),
                ('paymentStatus', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('partiel', 'Partiel'), ('en_cours', 'En cours'), ('remboursé', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=50)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'factures',
            },
        ),
    ]
