# Generated by Django 5.2.5 on 2025-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
