# Generated by Django 5.2.5 on 2025-10-04 22:53

import django.utils.timezone
import produits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(default=produits.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('categorie', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'produits',
            },
        ),
    ]
