# Generated by Django 5.2.5 on 2025-08-10 10:33

import vols.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('idVol', models.CharField(default=vols.models.generate_custom_vol_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=100)),
                ('flightNumber', models.CharField(max_length=20)),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('route_fromCode', models.CharField(max_length=10)),
                ('route_toCode', models.CharField(max_length=10)),
                ('schedule_departure', models.DateTimeField()),
                ('schedule_arrival', models.DateTimeField()),
                ('schedule_duration', models.CharField(max_length=20)),
                ('aircraft', models.CharField(max_length=100)),
                ('flight_class', models.CharField(choices=[('economy', 'Économie'), ('business', 'Affaires'), ('first', 'Première')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('limited', 'Limité'), ('full', 'Complet')], max_length=10)),
                ('seats_total', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('services', models.JSONField(default=list)),
                ('baggage_carry', models.CharField(max_length=100)),
                ('baggage_checked', models.CharField(max_length=100)),
                ('cancellation_flexible', models.BooleanField()),
                ('cancellation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_website', models.URLField()),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('lastUsed', models.DateTimeField(blank=True, null=True)),
                ('popularity', models.IntegerField()),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vols',
            },
        ),
    ]
