# Generated by Django 5.2.5 on 2025-08-10 10:33

import django.utils.timezone
import hebergements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('idHebergement', models.CharField(default=hebergements.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('priceRange', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rating', models.FloatField()),
                ('amenities', models.JSONField()),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('favorite', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastUsed', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('popularity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'hebergements',
            },
        ),
    ]
