# Generated by Django 5.2.5 on 2025-10-05 09:04

import commande_produits.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0002_alter_commande_id_client'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.CharField(default=commande_produits.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_commande', models.ForeignKey(db_column='id_commande', on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='commande.commande')),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='produits.produit')),
            ],
            options={
                'db_table': 'commande_produits',
                'unique_together': {('id_commande', 'id_produit')},
            },
        ),
    ]
