# Generated by Django 5.2.5 on 2025-08-10 10:33

import django.db.models.deletion
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idReservation', models.CharField(default=reservations.models.generate_reservation_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('vol', 'Vol'), ('voiture', 'Voiture'), ('hebergement', 'Hébergement'), ('activité', 'Activité')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lieu_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_arrivee', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
