# Generated by Django 5.2.5 on 2025-10-04 22:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(max_length=50)),
                ('statut_paiement', models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('échoué', 'Échoué'), ('remboursé', 'Remboursé')], default='en attente', max_length=20)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commande.commande')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
    ]
