# Generated by Django 5.2.5 on 2025-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut_paiement',
            field=models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('payée', 'Payée'), ('échoué', 'Échoué'), ('remboursé', 'Remboursé')], default='en attente', max_length=20),
        ),
    ]
