# Generated by Django 5.2.5 on 2025-10-04 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.CharField(max_length=10)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en attente', 'en attente'), ('payée', 'payée'), ('expédiée', 'expédiée'), ('annulée', 'annulée')], default='en attente', max_length=20)),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
    ]
