# Generated by Django 5.2.5 on 2025-10-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_adress_client_adresse'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client'),
        ),
    ]
