# Generated by Django 5.2.5 on 2025-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_commande_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en attente', 'en attente'), ('payée', 'payée'), ('livrée', 'livrée'), ('expédiée', 'expédiée'), ('annulée', 'annulée')], default='en attente', max_length=20),
        ),
    ]
