# Generated by Django 5.2.5 on 2025-08-10 10:33

import voitures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('idVoiture', models.CharField(default=voitures.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('pricePerDay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible'), ('maintenance', 'Maintenance')], max_length=20)),
                ('driverIncluded', models.BooleanField()),
                ('driverName', models.CharField(blank=True, max_length=100, null=True)),
                ('driverPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lastUsed', models.DateField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voitures',
            },
        ),
    ]
