# Generated by Django 5.2.5 on 2025-10-04 22:53

import clients.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.CharField(default=clients.models.generate_custom_client_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
