# Generated by Django 5.2.5 on 2025-10-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='adress',
        ),
    ]
