# Generated by Django 5.2.5 on 2025-10-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_address_client_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='adresse',
        ),
    ]
