# Generated by Django 5.2.5 on 2025-10-05 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id_inventaire', models.AutoField(primary_key=True, serialize=False)),
                ('mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('id_produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='produits.produit')),
            ],
            options={
                'db_table': 'inventaires',
            },
        ),
    ]
